export const initialProduct = [
    { id: 1, name: "Big Mac", price: 2, count: 0, src: "/images/big-mac.jpg" },
    { id: 2, name: "Flip Flops", price: 3, count: 0, src: "/images/flip-flops.jpg" },
    { id: 3, name: "Coca-Cola Pack", price: 5, count: 0, src: "/images/coca-cola-pack.jpg" },
    { id: 4, name: "Movie Ticket", price: 12, count: 0, src: "/images/movie-ticket.jpg" },
    { id: 5, name: "Book", price: 15, count: 0, src: "/images/book.jpg" },
    { id: 6, name: "Lobster Dinner", price: 45, count: 0, src: "/images/lobster-dinner.jpg" },
    { id: 7, name: "Video Game", price: 60, count: 0, src: "/images/video-game.jpg" },
    { id: 8, name: "Amazon Echo", price: 99, count: 0, src: "/images/amazon-echo.jpg" },
    { id: 9, name: "Year of Netflix", price: 100, count: 0, src: "/images/year-of-netflix.jpg" },
    { id: 10, name: "Air Jordans", price: 125, count: 0, src: "/images/air-jordans.jpg" },
    { id: 11, name: "Airpods", price: 199, count: 0, src: "/images/airpods.jpg" },
    { id: 12, name: "Gaming Console", price: 299, count: 0, src: "/images/gaming-console.jpg" },
    { id: 13, name: "Drone", price: 350, count: 0, src: "/images/drone.jpg" },
    { id: 14, name: "Smartphone", price: 699, count: 0, src: "/images/smartphone.jpg" },
    { id: 15, name: "Bike", price: 800, count: 0, src: "/images/bike.jpg" },
    { id: 16, name: "Kitten", price: 1500, count: 0, src: "/images/kitten.jpg" },
    { id: 17, name: "Pubby", price: 1500, count: 0, src: "/images/puppy.jpg" },
    { id: 18, name: "Auto Rickshaw", price: 2300, count: 0, src: "/images/auto-rickshaw.jpg" },
    { id: 19, name: "Horse", price: 2500, count: 0, src: "/images/horse.jpg" },
    { id: 20, name: "Acre of Farmland", price: 3000, count: 0, src: "/images/acre-of-farmland.jpg" },
    { id: 21, name: "Designer Handbag", price: 5500, count: 0, src: "/images/designer-handbag.jpg" },
    { id: 22, name: "Hot Tub", price: 6000, count: 0, src: "/images/hot-tub.jpg" },
    { id: 23, name: "Luxury Wine", price: 7000, count: 0, src: "/images/luxury-wine.jpg" },
    { id: 24, name: "Diamond Ring", price: 10000, count: 0, src: "/images/diamong-ring.jpg" },
    { id: 25, name: "Jet Ski", price: 12000, count: 0, src: "/images/jet-ski.jpg" },
    { id: 26, name: "Rolex", price: 15000, count: 0, src: "/images/rolex.jpg" },
    { id: 27, name: "Ford F-150", price: 30000, count: 0, src: "/images/ford-f-150.jpg" },
    { id: 28, name: "Tesla", price: 75000, count: 0, src: "/images/tesla.jpg" },
    { id: 29, name: "Monster Truck", price: 150000, count: 0, src: "/images/monster-truck.jpg" },
    { id: 30, name: "Ferrari", price: 250000, count: 0, src: "/images/ferrari.jpg" },
    { id: 31, name: "Single Family Home", price: 300000, count: 0, src: "/images/single-family-home.jpg" },
    { id: 32, name: "Gold Bar", price: 700000, count: 0, src: "/images/gold-bar.jpg" },
    { id: 33, name: "McDonalds Franchise", price: 1500000, count: 0, src: "/images/mcdonalds-franchise.jpg" },
    { id: 34, name: "Superbowl Ad", price: 5250000, count: 0, src: "/images/superbowl-ad.jpg" },
    { id: 35, name: "Yacht", price: 7500000, count: 0, src: "/images/yacht.jpg" },
    { id: 36, name: "M1 Abrams", price: 8000000, count: 0, src: "/images/m1-abrams.jpg" },
    { id: 37, name: "Formula 1 Car", price: 15000000, count: 0, src: "/images/formula-1-car.jpg" },
    { id: 38, name: "Apache Helicopter", price: 31000000, count: 0, src: "/images/apache-helicopter.jpg" },
    { id: 39, name: "Manison", price: 45000000, count: 0, src: "/images/mansion.jpg" },
    { id: 40, name: "Make a Movie", price: 100000000, count: 0, src: "/images/make-a-movie.jpg" },
    { id: 41, name: "Boeing 747", price: 148000000, count: 0, src: "/images/boeing-747.jpg" },
    { id: 42, name: "Mona Lisa", price: 780000000, count: 0, src: "/images/mona-lisa.jpg" },
    { id: 43, name: "Skyscraper", price: 850000000, count: 0, src: "/images/skyscraper.jpg" },
    { id: 44, name: "Cruise Ship", price: 850000000, count: 0, src: "/images/cruise-ship.jpg" },
    { id: 45, name: "NBA Team", price: 2120000000, count: 0, src: "/images/nba-team.jpg" },
]
